# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=50)),
                ('opened', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('status_notes', models.CharField(max_length=100)),
                ('request_details', models.CharField(max_length=200)),
                ('supervisor_district', models.PositiveIntegerField(default=0)),
                ('case_id', models.PositiveIntegerField(default=0)),
                ('responsible_agency', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('updated', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('needs_recoding', models.BooleanField(default=False)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casedata.Point'),
        ),
    ]
