# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casedata', '0002_auto_20170212_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='address',
            new_name='human_address',
        ),
    ]
