# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casedata', '0006_auto_20170212_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='point',
        ),
    ]
